autoroles:
- channel: "autorole-channel"
  message: "Add ğŸ‘ reaction to this message to obtain role test-autorole. Add ğŸº reaction to obtain test-autorole-beer role. Remove your reaction to have role removed."
  role: test-autorole
  emoji: ğŸ‘
- channel: "autorole-channel"
  message: "Add ğŸ‘ reaction to this message to obtain role test-autorole. Add ğŸº reaction to obtain test-autorole-beer role. Remove your reaction to have role removed."
  role: test-autorole-beer
  emoji: ğŸº
